updates

diff --git a/mk-include/bin/vault-sem-get-secret b/mk-include/bin/vault-sem-get-secret
--- a/mk-include/bin/vault-sem-get-secret
+++ b/mk-include/bin/vault-sem-get-secret
@@ -8,32 +8,17 @@ do
 		secretToDo="v1/ci/kv/semaphore2/${secretToDo}"
 	fi
 
-	retries=0
-
+	echo -n "Injecting Secret ${secretToDo} - "
 	# shellcheck disable=SC2164
-	pushd "$HOME" &>/dev/null
+	pushd "${HOME}" >/dev/null 2>&1
 	retVal=$(( retVal + $? ))
-
-	while [[ 5 -gt $retries ]]; do
-		sleep $(( retries++ ))
-		echo -n "try #$retries - Injecting Secret ${secretToDo} - " >&2
-		vault kv get -field=script "$secretToDo" > ./__VAULT_TMPFILE && break
-		echo "Failed injecting secret==$secretToDo " >&2
-		rm -f ./__VAULT_TMPFILE
-	done
-
-	if [[ -f ./__VAULT_TMPFILE ]]; then
-		# shellcheck disable=SC1091
-		source ./__VAULT_TMPFILE && rm -f ./__VAULT_TMPFILE &>/dev/null && echo "Success injecting $secretToDo" >&2
-		errSt=$?
-	else
-		echo "All $retries retries failed.  Giving up!" >&2
-	fi
-	[[ $errSt != 0 ]] && echo "Failed injecting secret==$secretToDo" >&2
+	# shellcheck disable=SC1091
+	vault kv get -field=script "${secretToDo}" > ./__VAULT_TMPFILE && source ./__VAULT_TMPFILE && rm -f ./__VAULT_TMPFILE >/dev/null && echo "Success injecting $secretToDo"
+	errSt=$?
+	if [[ $errSt != 0 ]] ; then echo "Failed injecting secret==${secretToDo}" ; fi
 	retVal=$(( retVal + errSt ))
-
 	# shellcheck disable=SC2164
-	popd &>/dev/null
+	popd >/dev/null 2>&1
 	retVal=$(( retVal + $? ))
 done
 
@@ -41,7 +26,7 @@ done
 if [[ $retVal == 0 ]] ; then
 	true
 else
-	echo "Failure injecting some secret above, returning FALSE" >&2
+	echo "Failure injecting some secret above, returning FALSE"
 	false
 fi
 
